class PlayerAdvancedStatAndRank {
  var playerId;
  var playerName;
  var nickname;
  var teamId;
  var teamAbbreviation;
  var age;
  var gamesPlayed;
  var wins;
  var losses;
  var winPct;
  var minutes;
  var eOffRating;
  var offRating;
  var eDefRating;
  var defRating;
  var eNetRating;
  var netRating;
  var astPct;
  var astTov;
  var astRatio;
  var oRebPct;
  var dRebPct;
  var rebPct;
  var tmTovPct;
  var eTovPct;
  var efgPct;
  var tsPct;
  var usgPct;
  var eUsgPct;
  var ePace;
  var pace;
  var pacePer40;
  var pie;
  var poss;
  var fgm;
  var fga;
  var fgmPg;
  var fgaPg;
  var fgPct;
  var gamesPlayedRank;
  var winsRank;
  var lossesRank;
  var winPctRank;
  var minutesRank;
  var eOffRatingRank;
  var offRatingRank;
  var eDefRatingRank;
  var defRatingRank;
  var eNetRatingRank;
  var netRatingRank;
  var astPctRank;
  var astTovRank;
  var astRatioRank;
  var oRebPctRank;
  var dRebPctRank;
  var rebPctRank;
  var tmTovPctRank;
  var eTovPctRank;
  var efgPctRank;
  var tsPctRank;
  var usgPctRank;
  var eUsgPctRank;
  var ePaceRank;
  var paceRank;
  var pacePer40Rank;
  var pieRank;
  var possRank;
  var fgmRank;
  var fgaRank;
  var fgmPgRank;
  var fgaPgRank;
  var fgPctRank;

  PlayerAdvancedStatAndRank(dynamic json) {
    playerId = json[0];
    playerName = json[1];
    nickname = json[2];
    teamId = json[3];
    teamAbbreviation = json[4];
    age = json[5];
    gamesPlayed = json[6];
    wins = json[7];
    losses = json[8];
    winPct = json[9];
    minutes = json[10];
    eOffRating = json[11];
    offRating = json[12];
    eDefRating = json[14];
    defRating = json[15];
    eNetRating = json[17];
    netRating = json[18];
    astPct = json[20];
    astTov = json[21];
    astRatio = json[22];
    oRebPct = json[23];
    dRebPct = json[24];
    rebPct = json[25];
    tmTovPct = json[26];
    eTovPct = json[27];
    efgPct = json[28];
    tsPct = json[29];
    usgPct = json[30];
    eUsgPct = json[31];
    ePace = json[32];
    pace = json[33];
    pacePer40 = json[34];
    pie = json[36];
    poss = json[37];
    fgm = json[38];
    fga = json[39];
    fgmPg = json[40];
    fgaPg = json[41];
    fgPct = json[42];
    gamesPlayedRank = json[43];
    winsRank = json[44];
    lossesRank = json[45];
    winPctRank = json[46];
    minutesRank = json[47];
    eOffRatingRank = json[48];
    offRatingRank = json[49];
    eDefRatingRank = json[51];
    defRatingRank = json[52];
    eNetRatingRank = json[54];
    netRatingRank = json[55];
    astPctRank = json[57];
    astTovRank = json[58];
    astRatioRank = json[59];
    oRebPctRank = json[60];
    dRebPctRank = json[61];
    rebPctRank = json[62];
    tmTovPctRank = json[63];
    eTovPctRank = json[64];
    efgPctRank = json[65];
    tsPctRank = json[66];
    usgPctRank = json[67];
    eUsgPctRank = json[68];
    ePaceRank = json[69];
    paceRank = json[70];
    //pacePer40Rank = json[0];
    pieRank = json[72];
    //possRank = json[0];
    fgmRank = json[73];
    fgaRank = json[74];
    fgmPgRank = json[75];
    fgaPgRank = json[76];
    fgPctRank = json[77];
  }
}

class PlayerAdvancedStatAndRankList {
  List<PlayerAdvancedStatAndRank> items = [];

  PlayerAdvancedStatAndRankList(dynamic json) {
    for (var l in json[0]["rowSet"]) {
      items.add(PlayerAdvancedStatAndRank(l));
    }
  }
}
